<?php

declare(strict_types=1);

use App\VerifyTransaction;
use Httpful\Request;
use PHPUnit\Framework\TestCase;

class VerifyTransactionTest extends TestCase
{
    /**
     * @var VerifyTransaction
     */
    private $verifyTransaction;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->verifyTransaction = new VerifyTransaction();
    }

    public function testWithEmptyTxnRef()
    {
        self::assertEquals($this->verifyTransaction->verify(''), null);
    }

    public function testWithSomeTxnRef()
    {
        self::assertEquals($this->verifyTransaction->verify('hello'), false);
    }

    public function testCliche() {

    }
}
